### PR TITLE
feat(sample): costa-farber sampler, examples

### PR DESCRIPTION
**Pull request by corybrunson**
This addresses the specific idea in #6, based on the experimental code from myself and @peekxc posted there!

### CODE REVIEW

**Comment by corybrunson** [comment]
Two samplers are implemented, and i'm done for now. : ) I'm not sure what to make of the Xcode issues that fail on Travis-CI, and unfortunately i can't test them locally because i can't use Xcode to compile any more (since i only have an older version installed that causes issues with existing simplextree code).

**Comment by corybrunson** [comment]
The checks have passed! The issue appears to have been a `return;` call in `extend_f_bernoulli()` left over from experiments.

**Comment by peekxc** [comment]
Looks good to me! Thanks for the PR!

**Comment by corybrunson** [comment]
I'm not sure what happens when i push new commits to a branch that was previously merged, but some additional functionality is on its way though not yet ready for a PR.

**Pull request merged**
