### PR TITLE
geometric samplers and markdown syntax for all sampler documentation

### PR DESCRIPTION
**Pull request by corybrunson**
This PR

* changes the file `sample.R`, which defines abstract samplers, to `sample-abstract.R`,
* adds the file `sample-geometric.R`, which defines geometric samplers,
* removes the (already commented-out) `sample_complex()` function shell, and
* switches from classic roxygen2 to Markdown-flavored syntax in the documentation of both files, introducing several new `man-roxygen/ref-*.R` files for their references.

Note that i have not updated the documentation or run a check (due to hardware incompatibility), so i request help doing that before the PR is accepted! I apologize for any unforeseen bugs and will be glad to help address them.

### CODE REVIEW

**Comment by peekxc** [comment]
I don't understand the reason for the `make_geometric`. It just does a few checks on the input and then constructs a rips complex from the `dist` object (or point cloud). Isn't this functionality already precisely what `rips` does?

**Comment by corybrunson** [comment]
I have two motivations for `make_geometric()` (though the name is open to change): (1) It takes a `method` argument that allows the user to specify the constructor, and (2) it allows the user to store the point coordinates as vertex attributes. I envisioned constructors like `rips()` as separate, lower-level functions that should each do one thing simply and efficiently. (1) would be useful in workflows involving comparisons between constructors and (2) would be useful for annotation purposes (e.g. mappers), but both are rather higher-level needs.

That said, i realize now that i used `rips()` directly rather than let `method` control the choice of constructor. Sorry about that! There's only one constructor now, but the infrastructure should be ready to accommodate more. I'll get that up in a moment.

**Comment by peekxc** [comment]
> (2) it allows the user to store the point coordinates as vertex attributes

Ahh, I actually see how that could fit in here. It would nice to have a function that separation construction of the complex from the point cloud/metric itself. 

Actually, I think perhaps this function could be a bit more powerful and generic by leveraging `tdaunif`. Conceptually, what do you think of something like this: 

```R
sample_geometric <- function(n, dimension = 1L,  method = c("vietoris_rips", "cech"), space=c("square", "disk", "torus", ...), metric="default", coords = FALSE, ...)
```
where `...` are arguments to pass to the construction method (e.g. `rips`) or sampling function (e.g. `tdaunif::sample_sphere`), and `space` is one of the given suffixes in `tdaunif::sample_*`? We could also include default sensible metrics within these spaces, e.g. the great circle distance for spheres, if `metric` is left as the default. 

I know how to elegantly handle the sophisticated argument parsing and what not required here.

**Comment by corybrunson** [comment]
Oh, that's an interesting thought. It was indeed intended to work with tdaunif, but in its present form that would be done by composition / piping, so it does not force simplextree to add tdaunif as a `Depends` or `Suggests`. Do you think it would be worth the extra dependency to add this feature? My inclination is no, but i will think on it. (The feature is not just the convenience but also the default metric, which i hadn't thought of.)

**Comment by peekxc** [comment]
I think it would fine to add as an optional dependency via `Suggests` (not `Depends` though). One can use `requireNamespace` to detect the presence of `tdaunif`, for example, and if it's not installed then opt-to install it. See [this link](https://r-pkgs.org/description.html#dependencies) for the technical details. `tdaunif` is light enough (CRAN binaries are available, pure R sourcecode, very little dependencies, etc.) that at least I don't mind adding it.

Whether it is in the purview of this function and simplextree overall is up to us really. One could indeed accomplish the same for the simple examples using piping fairly easy, but then again other things could be automated in this function that are no so trivial, e.g. sampling rips complexes from uniformly distributed points on the n-sphere equipped with the great-circle distance

**Comment by corybrunson** [comment]
I'm OK with adding it to `Suggests` for now. **tdaunif** functions don't use ellipses, so we only have to worry about ambiguities when the constructor and sampler have arguments in common. This is most likely to happen with the radius and dimension parameters. Currently `rips()` uses `eps` and `dim` while **tdaunif** samplers use `ar` (for aspect ratio between radii) and `dim` where appropriate (e.g. samples from a sphere).

Something i've been meaning to bring up is how all the **tdaverse** packages should handle related arguments. One option is to use consistent parameters throughout, which would mean using, say, `sample_dim` and `complex_dim` in a higher-level function like this. Another option is to allow each package its own conventions. Even then, **tdaunif** and **simplextree** are both pretty low-level, so it might make sense for both to use `dim`.

Anyway, i can work on this, but only once i'm back home, since my travel laptop is still missing build tools and this would require some testing. Is that OK? I can get to it the weekend of mid-August.

**Comment by corybrunson** [comment]
On naming conventions, see also [Chapter 7](https://tidymodels.github.io/model-implementation-principles/standardized-argument-names.html) of the **tidymodels** conventions book.

**Comment by peekxc** [comment]
I have mixed feeling about tidy's conventions, haha. I think we shouldn't have to worry too much about it for this particular case

**Comment by corybrunson** [comment]
Basically i agree—i think it's a useful point of reference but i don't think we need to strictly follow it.

**Comment by corybrunson** [comment]
@peekxc would you be OK with making the tdaunif-based `sample_geometric()` idea an issue for now and completing this merge?

(I just did a bit of merging and debugging with your later commits to `master`.)

**Comment by peekxc** [comment]
It is merged! You should (hopefully?) have access to the changing the main branch. In the end I think too many branches were created; I couldn't keep up the energy to maintain them all separately to the point of a stable merge, resulting in the current state of the package

**Comment by corybrunson** [comment]
I'm so glad i'm not the only one who feels that way!

I guess i'd forgotten that i had access—i'll use it cautiously as i do a bit more here.

**Pull request merged**
