### PR TITLE
Erdos–Renyi engine + Kahle sampler

### PR DESCRIPTION
**Pull request by corybrunson**
Since the Kahle sampler is a straightforward application of `expand()`, and since modularizing the edge selection step will make upgrades easier, i'm PRing this branch again. These are all the major abstract (as opposed to geometric) generators i'm aware of; see e.g. [this survey](https://www.csun.edu/~ctoth/Handbook/chap22.pdf).

Note: The Costa–Farber sampler is refactored to call the Erdos–Renyi sampler, and benchmarking tests did not consistently find this or the previous implementation to be more efficient (by time or by memory).

Thanks again!

### CODE REVIEW

**Comment by corybrunson** [comment]
(Also, in general i don't know that unit tests are appropriate for samplers, but i can add some tests of the `stopifnot()` preludes if appropriate!)

**Comment by peekxc** [comment]
Just tossing ideas, what do you think of the idea of overloading a single sampler to have the functionality of four of these samplers? 

They all seem to have the parameters `n`, `prob`, and (optionally) `dim`. The semantics of whether and how to interpret each parameter could be deduced by an additional supplied `method` parameter. I'm thinking a signature similar too: 

```R
sample_complex <- function(n, prob, dim=NULL, method = c("costa farber", "linial meshulam wallach")){
  if (missing(method) || method == "costa farber"){
     ## checks specific to costa farber, etc. 
  } else if (...)
  # other methods 
}
```
Could also be called `rcomplex` to match R conventions like `rnorm` or `rbinom`, etc.

**Comment by corybrunson** [comment]
@peekxc this is a good consideration. Regarding the naming conventions, i tried to follow [those of R-igraph](https://igraph.org/r/doc/#S), and i think it'll be a common point of reference for users. What do you think about that versus R's base `r*()` functions? (For example, there will be no corresponding `d*()` or `p*()` or `q*()` functions for simplextree.)

I don't have as strong an opinion about using a `method` param rather than different functions. Certainly i would not overload a generic sampler with both abstract and geometric models, for example; maybe there could be functions `sample_abstract()` and `sample_geometric()`, each with their own methods? Still not sure i'd prefer that to separate functions, again with reference to R-igraph—none of which, i think, have options analogous to the `method` idea.

**Comment by corybrunson** [comment]
It's also worth noting that a larger collection of geometric sampling functions will be available to the user via piping `tdaunif::sample_*()` into a constructor that takes a coordinate matrix and a distance threshold.

**Comment by corybrunson** [comment]
@rrrlw since we've talked about naming conventions, maybe you can state an opinion on @peekxc 's idea above. As a user, would you prefer many separate functions or a more compactly-named function with a `method` parameter? You can try out the existing samplers by installing from the home `master` or from this branch on my fork. (Full disclosure: I'm leaning a bit more toward @peekxc 's suggestion.)

**Comment by peekxc** [comment]
I agree that in retrospect, having an `r*()` function with no equivalent `d*()`, `p*()`, etc. would be a bit confusing. I do like `sample_*` better. 

I know that is igraph's style, which is nice because it's very descriptive, and as you showed works well with the declarative style of programming. But the `igraph` package also has 900+ package functions, which can be a bit hard to navigate if you're just poking around trying to figure out how modify the graph to do something simple. 

I prefer to overload functions with similar functionality _when it's both possible and clean to do so_, which is consistent with the rest of the package. For example, instead of: 
```R
st <- simplextree()
st %>% insert_list(list(1:3))
st %>% insert_vector(1:3)
st %>% insert_matrix(matrix(1:3))
``` 
Which all do logically the same thing, I prefer the simpler: 
```R
st <- simplextree()
st %>% insert(x)
```
where `x` could be any of the three inputs chosen above, and the overload chosen is dependent on the type passed in. Of course I may be biased--I track the types of the variables I type pretty rigorously (which you have to do in C++), and I know not all R-users do this, which can lead to some confusion (e.g. `st %>% insert(as.list(1:8))` and `st %>% insert(1:8)` do _very_ different things.) But I think this happens enough in both R and Python that most users get it: like in Python `x + y` has different semantics if `x` and `y` are numbers (arithmetic add) vs. strings (concatenation) vs. lists (list concatenation).  

On the other hand, if the samplers have completely different parameters, then I think the declarative approach is the way to go, like in `tdaunif` it makes perfect sense since the shapes being sampled can be quite different, and the package has a narrow-enough focus (which is a good thing!) such that having 1 function per sampler is fine since they all yield the same type of output: they produce sampled points. 

So I think it just depends on whether the collection of samplers *can* be described by a single overload that isn't too crazy.

Looking at the four samplers we have (`sample_erdos_renyi`, `sample_linial_meshulam_wallach`, `sample_kahle`, and `sample_costa_farber`), they all have parameter `n` and `prob` + one has the parameter `dimension`. Even if the semantics are different for each parameter, that can all be handled in a single function call. Moreover, most of the code is identical between the functions or only slightly different, making this a good case for overloading imo. But if they are other abstract simplicial complex samplers that have completely different parameters, maybe separation would be better. 
 
That being said, if samplers were added which are more geometric in nature, they would probably need to follow the independent pattern. I actually have a function in a private package Im developing for my research where I use this sampler all the time: 

```R
r_geometric_complex <- function(n, radius, coords = FALSE, ...){
	xy <- cbind(runif(n), runif(n))
	d <- dist(xy, method = "euclidean")
	R <- rips(d, eps = 2*radius, ...)
	if (coords){ attr(R, "coords") <- xy }
	return(R)
}
```
 
Which samples a rips complex from `n` points uniformly sampled from the unit square (should probably use `tdaunif`). But then again, `simplextree` wasn't designed to specialized to specific geometric complexes: it's designed to work strictly in the domain of abstract simplicial complexes. The use of other data structures or techniques that take advantage of the  geometry (e.g. cover trees or delaunay triangulations or something) I think firmly belong in other packages.

**Comment by corybrunson** [comment]
> But I think this happens enough in both R and Python that most users get it

This addresses the greatest concern i had, and i think you're right about it. I'd still like to get an outside perspective, but i don't have any reservations about making the suggested changes before the merge.

As to geometric random complexes, i think i agree that only a basic function should exist in simplextree (roughly the one you're already using), and that any other raw material can be generated from tdaunif. That is, i think it would be appropriate to have a singe, very basic GRS sampler based on the unit square, analogous to what igraph provides. Is that your feeling too?

**Comment by peekxc** [comment]
> As to geometric random complexes, i think i agree that only a basic function should exist in simplextree (roughly the one you're already using), and that any other raw material can be generated from tdaunif. That is, i think it would be appropriate to have a singe, very basic GRS sampler based on the unit square, analogous to what igraph provides. Is that your feeling too?

Yeah that sounds like a good plan. Actually, the documentation page for said sampler could serve as a nice reference to refer users to the existence of other packages, e.g. `tdaunif`, and to showcase the functionality of what `simplextree` tries to achieve: want a delaunay complex on a torus? Here's a package to compute the delaunay triangulation, and here's a sampler from `tdaunif` to get truly uniform points from a torus--you can represent it and play with it with `simplextree`, pass it onto `rgl` to visualize it, do whatever you want with it. Need a rips complex from a klein bottle? Same procedure, etc. Same with nerve complexes, cech complex, alpha complexes... and eventually I'll add a native witness complex function.

**Comment by corybrunson** [comment]
Note: It would now be very easy to add aliases for any samplers known by multiple names, whether any of multiple author names (e.g. `method = "wallach"`) or conceptual names (e.g. `method = "clique"`).

**Comment by rrrlw** [comment]
Thanks for the ping @corybrunson and apologies for the delayed response. I also lean toward overloading as @peekxc stated above; that might be a result of our experience w/ C++, but I think that R's S3 generics, in particular, make the case for overloading functions (especially for the `insert_list/matrix/vector` example above). Unless the functions are conceptually distinct in a crucial way or (for whatever reason) challenging to code as a single function, I'd lean toward a single function w/ an additional parameter and, if possible, a sensible default. Hope this helps!

**Comment by corybrunson** [comment]
For reference, the prototype geometric samplers are now pushed to [the `sample2` branch on my fork](https://github.com/corybrunson/simplextree/tree/sample2)! These can be amended as needed to match conventions decided for the abstract samplers.

**Pull request merged**
